import React, { useMemo, useState } from "react";
import { AlertTriangle, BarChart3, DollarSign, RefreshCw, ShieldCheck, TrendingUp } from "lucide-react";

const rows = [
  { task:"store_reading", provider:"Gemini", runs:34, cost:18.7, cap:150, status:"ok" },
  { task:"ad_copy_generation", provider:"OpenAI", runs:148, cost:92.4, cap:300, status:"ok" },
  { task:"image_generation", provider:"Replicate", runs:28, cost:126.0, cap:400, status:"watch" },
  { task:"video_generation", provider:"Runway", runs:7, cost:196.0, cap:300, status:"risk" },
  { task:"risk_review", provider:"Anthropic", runs:55, cost:41.2, cap:200, status:"ok" },
];

const statusMap = { ok:["طبيعي","green"], watch:["مراقبة","amber"], risk:["مرتفع","red"] };

export default function CostMonitorPage(){
  const [period,setPeriod]=useState("هذا الشهر");
  const total=useMemo(()=>rows.reduce((s,r)=>s+r.cost,0),[]);
  const cap=useMemo(()=>rows.reduce((s,r)=>s+r.cap,0),[]);
  const risk=rows.filter(r=>r.status==="risk").length;
  return <main className="page" dir="rtl"><style>{styles}</style><section className="title"><div><div className="eyebrow"><DollarSign size={15}/> Cost Monitor</div><h1>مراقبة تكلفة الذكاء الاصطناعي</h1><p>تكلفة حسب المهمة والمزود ومساحة العمل، مع حدود وتنبيهات تمنع استنزاف الميزانية.</p></div><button className="primary"><RefreshCw size={16}/> تحديث</button></section><section className="stats"><Stat title="إجمالي الصرف" value={`$${total.toFixed(1)}`}/><Stat title="الحد الشهري" value={`$${cap}`}/><Stat title="استهلاك تقريبي" value={`${Math.round(total/cap*100)}%`}/><Stat title="مسارات خطر" value={risk}/></section><section className="layout"><article className="card"><h2>التكلفة حسب المهمة</h2><div className="table"><div className="head"><span>المهمة</span><span>المزود</span><span>التشغيلات</span><span>التكلفة</span><span>الحد</span><span>الحالة</span></div>{rows.map(r=><div className="row" key={r.task}><span>{r.task}</span><span>{r.provider}</span><span>{r.runs}</span><span>${r.cost}</span><span>${r.cap}</span><Status value={r.status}/></div>)}</div></article><aside className="card"><h2>تنبيهات التكلفة</h2><div className="alert"><AlertTriangle size={17}/> توليد الفيديو يقترب من الحد ويحتاج موافقة فوق $3 لكل تشغيل.</div><div className="alert ok"><ShieldCheck size={17}/> النشر التلقائي غير مرتبط بأي تكلفة تشغيل.</div><div className="mini-chart">{rows.map(r=><span key={r.task} style={{height:`${Math.max(12,Math.round(r.cost/r.cap*100))}%`}}/>)}</div></aside></section></main>}
function Status({value}){const [label,tone]=statusMap[value];return <span className={`status ${tone}`}>{label}</span>}
function Stat({title,value}){return <article className="stat"><span>{title}</span><strong>{value}</strong></article>}
const styles=`.page{min-height:calc(100vh - 80px);padding:24px;background:#f7f8f4;color:#1f241d;font-family:Inter,"Segoe UI",Tahoma,Arial,sans-serif}.title,.stat,.card{background:#fff;border:1px solid #e4e7df;border-radius:24px;box-shadow:0 8px 26px rgba(24,38,18,.035)}.title{padding:20px;display:flex;justify-content:space-between;gap:16px;margin-bottom:16px}.eyebrow{width:fit-content;min-height:30px;padding:0 11px;border-radius:999px;display:inline-flex;align-items:center;gap:7px;color:#176b2c;background:#eef7e9;font-size:12px;font-weight:900;margin-bottom:10px}.title h1{margin:0;font-size:34px}.title p{color:#6f746b;line-height:1.8}.primary{height:42px;border:0;border-radius:16px;background:#176b2c;color:#fff;padding:0 16px;display:flex;gap:8px;align-items:center;font-weight:900}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:16px}.stat{padding:16px}.stat span{color:#6f746b;font-size:13px;font-weight:900}.stat strong{display:block;margin-top:8px;font-size:30px}.layout{display:grid;grid-template-columns:minmax(0,1fr)330px;gap:16px}.card{padding:18px}.table{border:1px solid #e4e7df;border-radius:18px;overflow:hidden}.head,.row{display:grid;grid-template-columns:1.2fr .8fr .7fr .7fr .7fr .7fr;gap:10px;padding:13px 14px;align-items:center}.head{background:#f7f8f4;color:#6f746b;font-size:12px;font-weight:900}.row{border-top:1px solid #e4e7df}.row span:first-child{font-weight:900}.status{width:fit-content;border-radius:999px;padding:6px 10px;font-size:11px;font-weight:900}.green{background:#f0fdf4;color:#166534}.amber{background:#fffbeb;color:#92400e}.red{background:#fef2f2;color:#991b1b}.alert{border:1px solid #fde68a;background:#fff7e6;color:#92400e;border-radius:18px;padding:13px;display:flex;gap:8px;line-height:1.8;font-size:12px;font-weight:800;margin-bottom:10px}.alert.ok{background:#f0fdf4;border-color:#bbf7d0;color:#166534}.mini-chart{height:220px;border:1px solid #e4e7df;border-radius:18px;padding:16px;display:flex;align-items:flex-end;gap:12px}.mini-chart span{flex:1;background:#176b2c;border-radius:999px 999px 6px 6px}@media(max-width:1000px){.stats,.layout{grid-template-columns:1fr}.table{overflow:auto}.head,.row{min-width:780px}}`;