import React, { useMemo, useState } from "react";
import { CircleAlert, Globe2, RefreshCw, SearchCheck, Store } from "lucide-react";

const seed = [
  { id:"website", name:"رابط المتجر", type:"Website", status:"scan_completed", confidence:86, output:"3 منتجات، 3 تصنيفات، 2 أصول", last:"منذ 12 دقيقة" },
  { id:"instagram", name:"Instagram", type:"Social", status:"scan_completed", confidence:74, output:"نبرة ودية وثيمات هدايا", last:"منذ ساعة" },
  { id:"tiktok", name:"TikTok", type:"Social", status:"manual", confidence:30, output:"رابط مدخل يدويًا", last:"لم يحلل" },
  { id:"commerce", name:"Salla / Commerce", type:"Commerce", status:"empty", confidence:0, output:"غير متصل", last:"لم يبدأ" },
];

const statusMap = { empty:["لم يبدأ","slate"], manual:["يدوي","slate"], pending_scan:["قيد الفحص","amber"], scan_completed:["تم التحليل","green"], failed:["فشل","red"], connected:["مرتبط","green"] };

export default function DataSourcesHubPage(){
  const [sources,setSources]=useState(seed);
  const [selectedId,setSelectedId]=useState(seed[0].id);
  const selected=sources.find(s=>s.id===selectedId)||sources[0];
  const stats=useMemo(()=>({total:sources.length,done:sources.filter(s=>s.status==="scan_completed").length,manual:sources.filter(s=>s.status==="manual").length,avg:Math.round(sources.reduce((a,b)=>a+b.confidence,0)/sources.length)}),[sources]);
  const scan=(id)=>{setSources(p=>p.map(s=>s.id===id?{...s,status:"pending_scan",output:"جاري التحليل...",last:"الآن"}:s));setTimeout(()=>setSources(p=>p.map(s=>s.id===id?{...s,status:"scan_completed",confidence:78,output:"تم جمع بيانات جديدة وتحديث التوصيات",last:"الآن"}:s)),800)};
  return <main className="page" dir="rtl"><style>{styles}</style><section className="title"><div><div className="eyebrow"><Globe2 size={15}/> Data Sources</div><h1>مصادر البيانات والتكاملات</h1><p>مركز فحص المتجر، تحليل الحسابات العامة، والربط الرسمي. كل مصدر له حالة وثقة ومخرجات تنعكس على باقي الشاشات.</p></div><button className="primary" onClick={()=>scan(selected.id)}><SearchCheck size={16}/> فحص المصدر المحدد</button></section><section className="stats"><Stat title="المصادر" value={stats.total}/><Stat title="تم التحليل" value={stats.done}/><Stat title="يدوي" value={stats.manual}/><Stat title="متوسط الثقة" value={`${stats.avg}%`}/></section><section className="layout"><article className="card"><h2>المصادر</h2><div className="source-list">{sources.map(s=><button key={s.id} className={selectedId===s.id?"selected":""} onClick={()=>setSelectedId(s.id)}><div><strong>{s.name}</strong><span>{s.type} · {s.output}</span></div><Status value={s.status}/></button>)}</div></article><aside className="card detail"><div className="icon"><Store size={24}/></div><h2>{selected.name}</h2><p>{selected.type}</p><Info label="الحالة" value={statusMap[selected.status][0]}/><Info label="الثقة" value={`${selected.confidence}%`}/><Info label="آخر فحص" value={selected.last}/><Info label="المخرجات" value={selected.output}/><button className="secondary" onClick={()=>scan(selected.id)}><RefreshCw size={16}/> إعادة الفحص</button><div className="warning"><CircleAlert size={17}/> النتائج المجموعة تحتاج مراجعة قبل استخدامها كمصدر نهائي للحملات.</div></aside></section></main>
}
function Status({value}){const [label,tone]=statusMap[value]||statusMap.empty;return <span className={`status ${tone}`}>{label}</span>}
function Stat({title,value}){return <article className="stat"><span>{title}</span><strong>{value}</strong></article>}
function Info({label,value}){return <div className="info"><span>{label}</span><strong>{value}</strong></div>}
const styles=`.page{min-height:calc(100vh - 80px);padding:24px;background:#f7f8f4;color:#1f241d;font-family:Inter,"Segoe UI",Tahoma,Arial,sans-serif}.title,.stat,.card{background:#fff;border:1px solid #e4e7df;border-radius:24px;box-shadow:0 8px 26px rgba(24,38,18,.035)}.title{padding:20px;display:flex;justify-content:space-between;gap:16px;margin-bottom:16px}.eyebrow{width:fit-content;min-height:30px;padding:0 11px;border-radius:999px;display:inline-flex;align-items:center;gap:7px;color:#176b2c;background:#eef7e9;font-size:12px;font-weight:900;margin-bottom:10px}.title h1{margin:0;font-size:34px;letter-spacing:-.04em}.title p{color:#6f746b;line-height:1.8}.primary,.secondary{min-height:42px;border-radius:16px;padding:0 16px;display:flex;align-items:center;gap:8px;font-weight:900}.primary{border:0;background:#176b2c;color:#fff}.secondary{border:1px solid #e4e7df;background:#fff;margin-top:14px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:16px}.stat{padding:16px}.stat span{color:#6f746b;font-size:13px;font-weight:900}.stat strong{display:block;margin-top:8px;font-size:30px}.layout{display:grid;grid-template-columns:minmax(0,1fr)340px;gap:16px}.card{padding:18px}.card h2{margin:0 0 14px}.source-list{display:grid;gap:10px}.source-list button{border:1px solid #e4e7df;background:#fff;border-radius:18px;padding:13px;text-align:right;display:flex;justify-content:space-between;gap:12px;font-family:inherit}.source-list button.selected{border-color:#176b2c;background:#eef7e9}.source-list strong{display:block}.source-list span{display:block;color:#6f746b;margin-top:4px;font-size:12px}.status{border-radius:999px;padding:6px 10px;font-size:11px;font-weight:900;height:fit-content}.green{background:#f0fdf4;color:#166534}.amber{background:#fffbeb;color:#92400e}.slate{background:#f8fafc;color:#475569}.red{background:#fef2f2;color:#991b1b}.icon{width:54px;height:54px;background:#176b2c;color:#fff;display:grid;place-items:center;border-radius:18px;margin-bottom:12px}.detail p{color:#6f746b}.info{min-height:44px;border-bottom:1px solid #e4e7df;display:flex;justify-content:space-between;gap:12px;align-items:center}.info span{color:#6f746b;font-size:12px;font-weight:900}.warning{margin-top:14px;border:1px solid #fde68a;background:#fff7e6;color:#92400e;border-radius:18px;padding:13px;display:flex;gap:8px;line-height:1.8;font-size:12px;font-weight:800}@media(max-width:1000px){.stats,.layout{grid-template-columns:1fr}}`;